In [2]:
# reference: https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/

### Eigendecomposition of a Matrix

In [3]:
from numpy import array
from numpy.linalg import eig

A = array([[1,2,3],[4,5,6],[7,8,9]])

print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# calculate eigen decomposition
e_values, e_vectors = eig(A)
print (e_values)
print ('\n')
print (e_vectors)

[  1.61168440e+01  -1.11684397e+00  -9.75918483e-16]


[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [8]:
e_vectors[:,0] # is one of the 3 eigen vectors

array([-0.23197069, -0.52532209, -0.8186735 ])

In [12]:
# Reconstructing into original matrix
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy.linalg import eig

Q = e_vectors
R = inv(e_vectors)
L = diag(e_values)

reconstruncted_matrix = Q.dot(L).dot(R)

In [13]:
reconstruncted_matrix

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [15]:
# Dimensional reduction without loss
import numpy as np
x = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])
cov_mat = x.T.dot (x) # this is like covariance matrix with some scaling
print (cov_mat)
np.shape(x)

[[ 14.  28.]
 [ 28.  56.]]


(3, 2)

In [ ]:
cov_matN = np.cov(x.T)
print(cov_matN)