In [4]:
from sklearn.datasets import load_iris 
from sklearn import preprocessing
import numpy as np
from numpy import linalg as LA

iris = load_iris() 
 
numSamples, numFeatures = iris.data.shape 
X = iris.data

Xn = preprocessing.scale(X)

In [6]:
Xn.shape

(150, 4)

In [8]:
u,s,v = np.linalg.svd(Xn.T)

In [9]:
u # eigen vector

array([[-0.52237162, -0.37231836,  0.72101681,  0.26199559],
       [ 0.26335492, -0.92555649, -0.24203288, -0.12413481],
       [-0.58125401, -0.02109478, -0.14089226, -0.80115427],
       [-0.56561105, -0.06541577, -0.6338014 ,  0.52354627]])

In [11]:
s # eigen value

array([ 20.89551896,  11.75513248,   4.7013819 ,   1.75816839])

In [12]:
def project_data(X, U, k):  
    U_reduced = U[:,:k]
    return np.dot(X, U_reduced)

def recover_data(Z, U, k):  
    U_reduced = U[:,:k]
    return np.dot(Z, U_reduced.T)

In [13]:
Z = project_data(Xn, u, 2)  
print ('2D Reduced Data: \n')
print (Z)

2D Reduced Data: 

[[  2.26454173e+00  -5.05703903e-01]
 [  2.08642550e+00   6.55404729e-01]
 [  2.36795045e+00   3.18477311e-01]
 [  2.30419716e+00   5.75367713e-01]
 [  2.38877749e+00  -6.74767397e-01]
 [  2.07053681e+00  -1.51854856e+00]
 [  2.44571134e+00  -7.45626750e-02]
 [  2.23384186e+00  -2.47613932e-01]
 [  2.34195768e+00   1.09514636e+00]
 [  2.18867576e+00   4.48629048e-01]
 [  2.16348656e+00  -1.07059558e+00]
 [  2.32737775e+00  -1.58587455e-01]
 [  2.22408272e+00   7.09118158e-01]
 [  2.63971626e+00   9.38281982e-01]
 [  2.19229151e+00  -1.88997851e+00]
 [  2.25146521e+00  -2.72237108e+00]
 [  2.20275048e+00  -1.51375028e+00]
 [  2.19017916e+00  -5.14304308e-01]
 [  1.89407429e+00  -1.43111071e+00]
 [  2.33994907e+00  -1.15803343e+00]
 [  1.91455639e+00  -4.30465163e-01]
 [  2.20464540e+00  -9.52457317e-01]
 [  2.77416979e+00  -4.89517027e-01]
 [  1.82041156e+00  -1.06750793e-01]
 [  2.22821750e+00  -1.62186163e-01]
 [  1.95702401e+00   6.07892567e-01]
 [  2.05206331e+00 

In [14]:
X_recovered = recover_data(Z, u, 2)  
print ('Reconstructed Data: \n')
print (X_recovered)

Reconstructed Data: 

[[ -9.94649483e-01   1.06443573e+00  -1.30560624e+00  -1.24776881e+00]
 [ -1.33390869e+00  -5.71436925e-02  -1.22656880e+00  -1.22297912e+00]
 [ -1.35552506e+00   3.28842647e-01  -1.38309889e+00  -1.36017238e+00]
 [ -1.41786717e+00   7.42863254e-02  -1.35146108e+00  -1.34091750e+00]
 [ -9.96601277e-01   1.25363164e+00  -1.37425242e+00  -1.30697852e+00]
 [ -5.16206153e-01   1.95078853e+00  -1.17147437e+00  -1.07178148e+00]
 [ -1.24980914e+00   7.13102071e-01  -1.42000663e+00  -1.37844378e+00]
 [ -1.07470438e+00   8.17473916e-01  -1.29320617e+00  -1.24728778e+00]
 [ -1.63111533e+00  -3.96853762e-01  -1.38437415e+00  -1.39627698e+00]
 [ -1.31033493e+00   1.61166989e-01  -1.28164028e+00  -1.26728661e+00]
 [ -7.31541585e-01   1.56066151e+00  -1.23495125e+00  -1.15365807e+00]
 [ -1.15671107e+00   7.59708020e-01  -1.34945228e+00  -1.30601645e+00]
 [ -1.42581541e+00  -7.06057994e-02  -1.30771568e+00  -1.30435327e+00]
 [ -1.72825247e+00  -1.73250730e-01  -1.55413850e+00  -

In [15]:
print ('Approximation Error: \n')
print (LA.norm(X_recovered-Xn))

Approximation Error: 

5.01937723539
