<h3> Introduction to Numpy </h3>
In this section we will learn about numpy package that helps in working with arrays.
<h3> References </h3>
Python for Data Analysis, 2nd Edition <br>
<a href="https://docs.scipy.org/doc/numpy-dev/user/quickstart.html"> Numpy Tutorial </a><br>


When you are looking for functionality that is not available in Python core, you can import one of the many Python packages available. Numpy is one of such packages and it helps in working with arrays. 


In [1]:
import numpy as np
a = np.arange(15) # create one dimensional array initialized with values from 0 to 14
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
a = np.arange(15).reshape(3, 5)
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a0 =np.zeros( (3,4) )
a1 = np.ones( (3,4), dtype=int )
print (a0)
print (a1)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
np.linspace( 0, 2, 9 ) # 9 members from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [5]:
x = np.linspace( 0, 2*np.pi, 100 ) # create 100 members from 0 to 2*pi
# evaluate sin function at the above generated 100 points
f = np.sin(x)

In [6]:
# select a column (row) of a 2d array
a =  np.random.rand(4,5)
print (a)
a0 = a[:,0]
print (a0)
a0 = a[0, :]
print (a0)

[[ 0.44347554  0.23269608  0.01394293  0.22104404  0.13452663]
 [ 0.92808595  0.55162482  0.90107214  0.66858435  0.83087596]
 [ 0.58031796  0.02332929  0.69290616  0.85229098  0.21453575]
 [ 0.7144588   0.67824481  0.15093271  0.69373841  0.95547972]]
[ 0.44347554  0.92808595  0.58031796  0.7144588 ]
[ 0.44347554  0.23269608  0.01394293  0.22104404  0.13452663]


#### Indexing arrays

In [7]:
x = np.arange(10)
x[2:5]

array([2, 3, 4])

In [8]:
x[:3]  # access 0 to 3-1

array([0, 1, 2])

In [9]:
x[:4]  # skip last 4 elements 

array([0, 1, 2, 3])

In [10]:
x[1:7:2] # access starting at 1 with stride 2 upto < 7

array([1, 3, 5])

In [11]:
x[9:4:-2] # access starting at 9 with stride -2  

array([9, 7, 5])

In [12]:
x[::] # implicitly x[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[::-2]  #implicitly x[9:0:-2]

array([9, 7, 5, 3, 1])

In [14]:
y = np.arange(35).reshape(5,7)
print(y)
y[1:5:2,::3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

Exercise 1: Create a numpy array of size ten: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]. Write a python statement  to reverse the array. Hint: use indexing 

Exercise 2: Write Python code to create a 2d array with 1 on the border and 0 inside. Hint: Use indexing

Sample output:
[[ 1. 1. 1. 1. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 1. 1. 1. 1.]]

In [16]:
# Solution to Exercise
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


Exercise 3: Write Python code to create a 2d 8x8 array with alternating 0 and 1 pattern (chess board)

Expected output:
                                            
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]

In [17]:
# Solution to Exercise
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<h3>Basic Operations on Arrays</h3>

In [18]:
a = np.array( [20,30,40,50] )
b = np.array([0, 1, 2, 3])
c = a-b
print(c)
c = a**2
print (c)
c = 10*np.sin(a)
print(c)
c = a[a<40]
print (c)
c = a < 35
print (c)

[20 29 38 47]
[ 400  900 1600 2500]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[20 30]
[ True  True False False]


#### Operations on 2D arrays and matrices

In [19]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
C = A * B
print (C)

[[2 0]
 [0 4]]


In [20]:
C = A.dot(B)
print (C)

[[5 4]
 [3 4]]


In [21]:
C = np.dot(A, B)
print (C)

[[5 4]
 [3 4]]


In [22]:
MA = np.mat(A)
MB = np.mat(B)
MC = MA * MB
print(MC)

[[5 4]
 [3 4]]


#### Working with broadcast and  tile

In [23]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
print(A+B)

[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [24]:
# before addition B is broadcast as
B = np.array([[1, 2, 3],] * 3)
print(B)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
B = np.array([1, 2, 3])
print(B)
B[:, np.newaxis]

[1 2 3]


array([[1],
       [2],
       [3]])

In [26]:
print(A + B[:, np.newaxis])

[[12 13 14]
 [23 24 25]
 [34 35 36]]


In [27]:
# before addition B is broadcast as
np.array([[1, 2, 3],] * 3).transpose()

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [28]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.tile(np.array([1, 2, 3]), (3, 1))
print(B)
print(A+B)
print(A*B)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[12 14 16]
 [22 24 26]
 [32 34 36]]
[[11 24 39]
 [21 44 69]
 [31 64 99]]


In [29]:
d1 = np.array([0, 10, 30, 60, 100])
print(np.abs(d1-d1[:, np.newaxis]))

[[  0  10  30  60 100]
 [ 10   0  20  50  90]
 [ 30  20   0  30  70]
 [ 60  50  30   0  40]
 [100  90  70  40   0]]


<h3>Linear Algebra</h3>

In [30]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print (a)
at = a.transpose()
print(at)
a_inv = np.linalg.inv(a)
print (a_inv)

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
y = np.array([[5.], [7.]])
x = np.linalg.solve(a, y)
print (x)

[[-3.]
 [ 4.]]


#### Random Functions in Numpy

In [32]:
# list of 10 random numbers in  [0.0, 1.0)
rnum = np.random.random(10) 
print(rnum)
rnum = rnum/np.sum(rnum)
print(rnum)
print(np.sum(rnum))

[ 0.47129826  0.06762874  0.99716455  0.81687616  0.21648486  0.04789331
  0.86591     0.91455458  0.19557153  0.27693694]
[ 0.09676949  0.0138859   0.20474317  0.16772539  0.04444983  0.00983371
  0.17779328  0.18778125  0.0401558   0.05686218]
1.0


In [33]:
rnum = np.random.random((5,4))
print(rnum)

[[ 0.52400364  0.6020572   0.02464621  0.53418632]
 [ 0.46904541  0.75423459  0.73192378  0.38899606]
 [ 0.44252089  0.11448147  0.68827101  0.64254247]
 [ 0.94435778  0.3150289   0.88399766  0.65176018]
 [ 0.09318721  0.63941477  0.38201003  0.55801404]]


In [34]:
print(np.random.randint(1,6))
[ np.random.randint(1, 6) for _ in range(10) ]

3


[5, 3, 4, 3, 1, 3, 1, 1, 4, 1]

In [35]:
sa = np.array( [20,30,40,50,60,100,300,500,700,800] )
print(np.random.choice(sa))
[ np.random.choice(sa) for _ in range(5) ]

60


[50, 100, 60, 500, 300]

In [36]:
np.random.choice(sa,(2,3))

array([[700,  30, 500],
       [ 30,  30,  40]])

In [37]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['Christopher', 'Christopher', 'Christopher', 'pooh', 'pooh'], 
      dtype='<U11')

Exercise 4: Write a function that is called  with a parameter p, which is a probabilty value between 0 and 1. The function returns a 1 with a probability of p, and zeros with probability of (1-p).

In [39]:
A = np.array([[11, 12], [12, 14]])
B = np.array([[0, 1], [2, 3]])
print(A.shape)
C = np.vstack((A,B))
print(C)
print(C.shape)

(2, 2)
[[11 12]
 [12 14]
 [ 0  1]
 [ 2  3]]
(4, 2)


In [40]:
C = np.hstack((A,B))
print(C)
print(C.shape)

[[11 12  0  1]
 [12 14  2  3]]
(2, 4)


In [41]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 7.,  8.,  1.,  4.,  1.,  1.,  9.,  9.,  7.,  2.,  5.,  0.],
       [ 6.,  6.,  1.,  3.,  2.,  0.,  2.,  6.,  5.,  7.,  1.,  0.]])

In [42]:
x,y,z = np.hsplit(a,3)   # Split a into 3
print(x)
print(y)
print(z)

[[ 7.  8.  1.  4.]
 [ 6.  6.  1.  3.]]
[[ 1.  1.  9.  9.]
 [ 2.  0.  2.  6.]]
[[ 7.  2.  5.  0.]
 [ 5.  7.  1.  0.]]


In [43]:
x,y,z = np.hsplit(a,(3,4))   # Split a after the third and the fourth column
print(x)
print(y)
print(z)

[[ 7.  8.  1.]
 [ 6.  6.  1.]]
[[ 4.]
 [ 3.]]
[[ 1.  1.  9.  9.  7.  2.  5.  0.]
 [ 2.  0.  2.  6.  5.  7.  1.  0.]]


In [62]:
x,y = np.vsplit(a,2)
print(x)
print(y)

[[ 7.  8.  1.  4.  1.  1.  9.  9.  7.  2.  5.  0.]]
[[ 6.  6.  1.  3.  2.  0.  2.  6.  5.  7.  1.  0.]]


In [63]:
# Boolean Mask
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,7,2,8,6,9,5])
R = C[A<=5]
print(R)

[123 190 100]


In [64]:
# indexing with an integer array
C[[0, 2, 3, 1, 4, 1]]

array([123, 190,  99, 188,  77, 188])

Exercise 5: Extract from the array np.array([3,4,6,10,24,89,45,43,46,99,100]) with Boolean masking all the number

which are not divisible by 3

which are divisible by 5

which are divisible by 3 and 5

which are divisible by 3 and set them to 42